#!/usr/bin/env python3

import os
import sys

from helpers import get_user_timeline
from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./smile @screenname")
        
    tweet = get_user_timeline(sys.argv[1], 50)
    
    if tweet is None:
        sys.exit("error")
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    # analyze word
    for t in tweet:
    
        score = analyzer.analyze(t)
        if score > 0.0:
            print(colored("{} {}".format(score, t), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score,t), "red"))
        else:
            print(colored("{} {}".format(score,t), "yellow"))


    
if __name__ == "__main__":
    main()
